name: Add Jira Comment After Successful Merge

on:
  workflow_call:

jobs:
  add-jira-comment:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Extract Issue IDs from PR Description
      id: extract_issue_ids
      run: |
        CM_REGEX='#CM-[0-9]+'
        JIRA_REGEX='#([A-Z]+[A-Z0-9]*-[0-9]+)'
        
        # Get the pull request description
        PR_DESCRIPTION="${{ github.event.pull_request.body }}"

        # Extract all matching JIRA IDs
        CM_IDS=$(echo "$PR_DESCRIPTION" | grep -oE "$CM_REGEX" | tr -d '#' | paste -sd ',' -)
        OTHER_IDS=$(echo "$PR_DESCRIPTION" | grep -oE "$JIRA_REGEX" | grep -vE "$CM_REGEX" | tr -d '#' | paste -sd ',' -)

        # Extract repo name
        REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)

        # Extract developer's username and full name
        DEVELOPER_USERNAME="${{ github.event.pull_request.user.login }}"

        echo "Change-management IDs: $CM_IDS"
        echo "Other JIRA issue IDs: $OTHER_IDS"
        echo "Repo Name: $REPO_NAME"
        echo "Developer Full Name: $DEVELOPER_FULLNAME"
        echo "pr_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
        echo "cm_ids=$CM_IDS" >> $GITHUB_ENV
        echo "jira_ids=$OTHER_IDS" >> $GITHUB_ENV
        echo "repo_name=$REPO_NAME" >> $GITHUB_ENV
        echo "developer_username=$DEVELOPER_USERNAME" >> $GITHUB_ENV

    - name: Checkout jira-integration repository content
      uses: actions/checkout@v4
      with:
        repository: jgmeet/jira-integration
        path: jira-integration

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./jira-integration

    - name: Send Slack Notifications
      env:
        EMAIL: ${{ secrets.EMAIL }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        CM_IDS: ${{ env.cm_ids }}
        PR_URL: ${{ env.pr_url }}
        WORKFLOW_RUN: ${{ 'merged' }}
      run: node slackNotifications.js
      working-directory: ./jira-integration

    - name: Adding comment to issues
      env:
        EMAIL: ${{ secrets.EMAIL }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        CM_IDS: ${{ env.cm_ids }}
        JIRA_IDS: ${{ env.jira_ids }}
        REPO_NAME: ${{ env.repo_name }}
        PR_URL: ${{ env.pr_url }}
        BRANCH_NAME: ${{ github.ref_name }}
        DEVELOPER_USERNAME: ${{ env.developer_username }}
      run: node addComment.js
      working-directory: ./jira-integration
